### ISSUE TITLE
Error when build runs and no pull request is present

### ISSUE THREAD

**Issue by sam-higton** [comparaonline/pronto-circleci#3]
Hey,

I'm getting the following error when a circleci build runs, and there isn't a pull request present yet

    bundler: failed to load command: pronto-circleci 
    (/home/circleci/repo/vendor/bundle/ruby/2.3.0/bin/pronto-circleci)
    NoMethodError: undefined method `split' for nil:NilClass
      /home/circleci/repo/vendor/bundle/ruby/2.3.0/gems/pronto-circleci-
    1.0.0/lib/pronto/circleci.rb:13:in `pull_requests_urls'
      /home/circleci/repo/vendor/bundle/ruby/2.3.0/gems/pronto-circleci-
    1.0.0/lib/pronto/circleci.rb:9:in run'
      /home/circleci/repo/vendor/bundle/ruby/2.3.0/gems/pronto-circleci-1.0.0/exe/pronto-circleci:5:in <top (required)>'
      /home/circleci/repo/vendor/bundle/ruby/2.3.0/bin/pronto-circleci:22:in 'load'
      /home/circleci/repo/vendor/bundle/ruby/2.3.0/bin/pronto-circleci:22:in '<top (required)>'
    Exited with code 1

Is there something I could be doing wrong, or is this a bug?

**Comment by dortegan** [comment]
Fixed [here](https://github.com/comparaonline/pronto-circleci/pull/5).
